[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "inotia00 ReVanced"
included-patches = "'Disable landscape mode'"
excluded-patches = "'Custom branding icon Revancify blue' 'Custom package name' 'MicroG support' 'Translations'"
