[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"

[Sync]
apkmirror-dlurl = "https://apkmirror.com/apk/red-apps-ltd/sync-for-reddit/"
build-mode = "both"
version = "19.0.22"
excluded-patches = "disable-sync-for-lemmy-bottom-sheet"

[Instagram]
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"
build-mode = "both"

[Icon Pack]
apkmirror-dlurl = "https://apkmirror.com/apk/smart-launcher-team/icon-pack-studio/"
build-mode = "both"

[Trakt]
apkmirror-dlurl = "https://apkmirror.com/apk/trakt/trakt/"
build-mode = "both"

