[YouTube-Extended]
enabled = "true"
app-name = "YouTube"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "ReVanced"
build-mode = "module"
excluded-patches = "'Vanced MicroG support' 'Premium heading'"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
